// FG-576 step 9: argv captured from both fake providers has no unconstructed operand.
import { afterEach, beforeEach, test } from "node:test";
import assert from "node:assert/strict";
import { chmodSync, copyFileSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { CODEX_CARRIER_ORIENTATION_MARKER, CODEX_CARRIER_SOURCE_REL, CODEX_CARRIER_SPLICE_MARKER, codexCarrierPath, publishSeedGeneration, resolveSeedGeneration } from "../v2/seed-generation.js";
import { stageAgentProtocols } from "../v2/seed-generation.testkit.js";
const here = dirname(fileURLToPath(import.meta.url)), repo = resolve(here, "..", ".."), cli = ["--import", join(repo, "bin", "forge-loader.mjs"), join(repo, "src", "cli", "index.ts")];
let base = "", home = "", project = "", bin = "", state = "", record = "";
const policy = (profile: string) => `schema_version: 2\nmodel_profiles:\n  claude:\n    provider: anthropic\n    auth: api\n    map:\n      default: { model: claude-sonnet-4-6, cost_tier: standard }\n  codex:\n    provider: openai\n    auth: subscription\n    map:\n      default: { model: gpt-5.6-terra, cost_tier: standard }\ndefaults:\n  profile: ${profile}\n  activity: {}\n`;
function run(args: string[]) { const r = spawnSync(process.execPath, [...cli, ...args], { cwd: project, encoding: "utf8", timeout: 30_000, env: { ...process.env, FORGE_HOME: home, FORGE_DB_PATH: join(home, "forge.db"), FORGE_CODEX_DIR: state, FORGE_ORCHESTRATORS_DIR: join(base, "orchestrators"), PATH: `${bin}:${process.env.PATH ?? ""}`, FAKE_CLAUDE_RECORD: record, FAKE_CODEX_RECORD: record, ANTHROPIC_API_KEY: "fixture" } }); return { status: r.status, stderr: r.stderr ?? "" }; }
beforeEach(() => { base = mkdtempSync(join(tmpdir(), "fg576-argv-")); home = join(base, "home"); project = join(base, "project"); bin = join(base, "bin"); state = join(base, "state"); record = join(base, "record.json"); for (const d of [home, project, bin, state]) mkdirSync(d, { recursive: true }); writeFileSync(join(project, "CLAUDE.md"), "<!-- forge:orchestrator-start -->\n"); copyFileSync(join(here, "__fixtures__", "fake-claude.js"), join(bin, "claude")); copyFileSync(join(here, "__fixtures__", "fake-codex.js"), join(bin, "codex")); chmodSync(join(bin, "claude"), 0o755); chmodSync(join(bin, "codex"), 0o755); writeFileSync(join(state, "auth.json"), "{}"); const release = join(base, "release"); mkdirSync(join(release, "seeds", "workflows"), { recursive: true }); mkdirSync(join(release, "seeds", "runtimes"), { recursive: true }); mkdirSync(join(release, "seeds", "codex"), { recursive: true }); writeFileSync(join(release, "seeds", "workflows", "x.yml"), "name: x\nsteps: []\n"); writeFileSync(join(release, "seeds", "runtimes", "x.yml"), "kind: x\n"); stageAgentProtocols(join(release, "seeds")); writeFileSync(join(release, "seeds", "orchestrator-template.md"), "<!-- forge:orchestrator-start -->\nx\n<!-- forge:orchestrator-end -->\n"); writeFileSync(join(release, "seeds", CODEX_CARRIER_SOURCE_REL), `# x\n${CODEX_CARRIER_ORIENTATION_MARKER}\n${CODEX_CARRIER_SPLICE_MARKER}\n`); publishSeedGeneration({ home, assetsDir: release, trustedAssetRoot: () => release }); });
afterEach(() => rmSync(base, { recursive: true, force: true }));
test("FG-576 D6: recorded argv is closed for both adapters and dash operands are refused before spawn", () => {
  writeFileSync(join(home, "model-policy.yml"), policy("claude")); let r = run(["orchestrator"]); assert.equal(r.status, 0, r.stderr); let argv = (JSON.parse(readFileSync(record, "utf8")) as { argv: string[] }).argv; assert.deepEqual(argv.filter((x) => x.startsWith("-")), ["-n", "--model", "--session-id", "--append-system-prompt-file"]); assert.equal(argv.filter((x) => x === "--model").length, 1);
  writeFileSync(join(home, "model-policy.yml"), policy("codex")); r = run(["orchestrator"]); assert.equal(r.status, 0, r.stderr); argv = (JSON.parse(readFileSync(record, "utf8")) as { argv: string[] }).argv; assert.deepEqual(argv.filter((x) => x.startsWith("-") || x === "resume"), ["--model", "--cd", "-c"]); const carrier = argv[argv.indexOf("-c") + 1]!; assert.equal(carrier, `experimental_instructions_file=${codexCarrierPath(resolveSeedGeneration(home)!)}`);
  for (const tokens of [["--model", "evil"], ["--cd", "/tmp/evil"], ["-c", "experimental_instructions_file=/tmp/evil"], ["--", "--model", "evil"]]) { r = run(["orchestrator", "--", ...tokens]); assert.notEqual(r.status, 0); assert.match(r.stderr, /D6|cannot be passed through/); }
});
