// FG-346: the generator emits a policy that ROUND-TRIPS through the production load
// path (loader version gate + Zod, not safeParse), rejects invented role keys / stale
// profiles, and marks runtime-fronted (pi/groq) structured capabilities tool_capable.

import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateModelPolicy, InvalidSelectionError } from "./model-policy-generator.js";
import { offerableChoices, type ProfileChoice } from "./model-policy-choices.js";
import { loadModelPolicy } from "./loader.js";
import type { AuthProbe } from "./provider-doctor.js";

const ANTHROPIC_AND_OPENAI: AuthProbe[] = [
  { provider: "anthropic", mode: "subscription", status: "available", detail: "ok" },
  { provider: "openai", mode: "subscription", status: "available", detail: "ok" },
];

const WITH_GROQ: AuthProbe[] = [
  { provider: "anthropic", mode: "subscription", status: "available", detail: "ok" },
  { provider: "groq", mode: "api", status: "available", detail: "GROQ_API_KEY set" },
];

function name(choices: ProfileChoice[], n: string): string {
  const c = choices.find((x) => x.profileName === n);
  if (!c) throw new Error(`test setup: no choice ${n} (have ${choices.map((x) => x.profileName).join(", ")})`);
  return c.profileName;
}

// Round-trip a YAML string through the PRODUCTION loader (version gate + Zod) by
// writing it to a throwaway FORGE_HOME and calling loadModelPolicy.
function loadViaProductionLoader(yaml: string): unknown {
  const prev = process.env.FORGE_HOME;
  const dir = mkdtempSync(join(tmpdir(), "fg346-gen-"));
  process.env.FORGE_HOME = dir;
  try {
    writeFileSync(join(dir, "model-policy.yml"), yaml);
    return loadModelPolicy({});
  } finally {
    if (prev === undefined) delete process.env.FORGE_HOME;
    else process.env.FORGE_HOME = prev;
    rmSync(dir, { recursive: true, force: true });
  }
}

test("generator: mixed Anthropic/OpenAI policy round-trips through the production loader", () => {
  const choices = offerableChoices(ANTHROPIC_AND_OPENAI);
  const { yaml, policy } = generateModelPolicy({
    choices,
    defaultProfile: name(choices, "anthropic-subscription-sonnet"),
    activity: {
      default: name(choices, "anthropic-subscription-sonnet"),
      reasoning: name(choices, "anthropic-subscription-opus"),
      review: name(choices, "anthropic-subscription-haiku"),
      fast: name(choices, "anthropic-subscription-haiku"),
    },
    rolePins: {
      "research-primary": name(choices, "anthropic-subscription-sonnet"),
      "research-skeptic": name(choices, "openai-subscription-codex"),
    },
  });

  // Header + explicit schema_version.
  assert.match(yaml, /^# forge model-policy — GENERATED by `forge setup`/);
  assert.match(yaml, /schema_version: 2/);

  // Round-trips through loader gate + Zod without throwing.
  const loaded = loadViaProductionLoader(yaml) as { schema_version: number; defaults: { activity: Record<string, string> }; model_profiles: Record<string, { map: Record<string, unknown> }> };
  assert.equal(loaded.schema_version, 2);

  // Every defaults.activity target has a resolvable map entry (explicit or default).
  for (const [cap, profileName] of Object.entries(loaded.defaults.activity)) {
    const map = loaded.model_profiles[profileName]!.map;
    assert.ok(map[cap] ?? map["default"], `capability '${cap}' unresolved on profile '${profileName}'`);
  }

  // In-memory policy object agrees on schema_version.
  assert.equal(policy.schema_version, 2);
});

test("generator: an overrides.agents key that is not a known role throws", () => {
  const choices = offerableChoices(ANTHROPIC_AND_OPENAI);
  assert.throws(
    () =>
      generateModelPolicy({
        choices,
        defaultProfile: name(choices, "anthropic-subscription-sonnet"),
        activity: { default: name(choices, "anthropic-subscription-sonnet") },
        rolePins: { "reserch-skpetic": name(choices, "openai-subscription-codex") },
      }),
    InvalidSelectionError,
  );
});

test("generator: a reference to a profile that was never offered throws", () => {
  const choices = offerableChoices(ANTHROPIC_AND_OPENAI);
  assert.throws(
    () =>
      generateModelPolicy({
        choices,
        defaultProfile: "anthropic-bedrock-sonnet", // not offered
        activity: { default: "anthropic-bedrock-sonnet" },
        rolePins: {},
      }),
    InvalidSelectionError,
  );
});

test("generator: a groq (runtime-fronted) structured capability emits tool_capable: true and runtime", () => {
  const choices = offerableChoices(WITH_GROQ);
  const groq = name(choices, "groq-api-kimi");
  const { yaml, policy } = generateModelPolicy({
    choices,
    defaultProfile: groq,
    activity: { default: groq, reasoning: groq, review: groq, fast: groq },
    rolePins: {},
  });
  assert.match(yaml, /runtime: pi-apikey/);
  const profile = policy.model_profiles[groq]!;
  assert.equal(profile.runtime, "pi-apikey");
  for (const entry of Object.values(profile.map)) {
    assert.equal(entry.tool_capable, true, "every groq map entry must be tool_capable");
  }
  // And it round-trips through the production loader.
  assert.doesNotThrow(() => loadViaProductionLoader(yaml));
});
