// FG-624 — duration-aware partitioning of the root integration tier.
//
// Node's `--test-shard=k/N` partitions by FILE INDEX, so which shard gets the
// slow files is arbitrary: on CI three shards finished in ~2.5-3 min while the
// fourth ran 5m25s, and adding ONE file reshuffled the partition and pushed it
// past the 6-minute job ceiling — a suite reporting `pass 670 / fail 0` killed
// by the job clock. This module replaces that with a greedy longest-processing-
// time bin-pack over measured per-file durations
// (scripts/integration-timings.json, regenerated by
// scripts/measure-integration-timings.ts).
//
// Selection stays in scripts/run-integration-tests.sh — it discovers the files
// and pipes them here on stdin; this module only decides WHICH SHARD each one
// lands in. Two properties matter more than balance and are pinned by
// src/test-shards.test.ts:
//
//   1. A file missing from the manifest still runs. It gets a pessimistic
//      default weight and is placed like any other. A partition that can drop a
//      file yields a green CI that proves nothing — worse than the timeout it
//      replaces.
//   2. The shards are a disjoint cover: union == input, no file in two shards.
//      With explicit per-shard file lists that is this code's job, not Node's.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

export const INTEGRATION_TIMINGS_PATH = join(REPO_ROOT, "scripts", "integration-timings.json");

export type Timings = Record<string, number>;

/**
 * Weight for a file the manifest doesn't mention. Pessimistic on purpose (p75
 * of the measured files, not the median): an unmeasured file is usually a NEW
 * file, and the cost of guessing low is a shard that blows the 6-minute
 * ceiling, while the cost of guessing high is only a slightly uneven partition.
 * An empty/missing manifest makes every weight equal, which degrades LPT to
 * round-robin over the sorted list — still a valid disjoint cover.
 */
export function defaultWeight(timings: Timings): number {
  const values = Object.values(timings).filter((v) => Number.isFinite(v) && v > 0);
  if (values.length === 0) return 1;
  values.sort((a, b) => a - b);
  return values[Math.min(values.length - 1, Math.floor(values.length * 0.75))]!;
}

export function loadTimings(path: string = INTEGRATION_TIMINGS_PATH): Timings {
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch {
    // A missing manifest must not stop the tier from running.
    return {};
  }
  const parsed = JSON.parse(raw) as { files?: Timings };
  const files = parsed.files ?? {};
  // Entries for deleted files are simply never looked up — no error, no drop.
  return Object.fromEntries(
    Object.entries(files).filter(([, ms]) => typeof ms === "number" && Number.isFinite(ms) && ms > 0),
  );
}

export function shardCost(files: readonly string[], timings: Timings, fallback = defaultWeight(timings)): number {
  return files.reduce((sum, f) => sum + (timings[f] ?? fallback), 0);
}

/**
 * Greedy longest-processing-time bin-pack: heaviest file first, each placed on
 * the shard that is currently lightest. LPT is the standard choice here — it is
 * a single pass, needs no search, and is provably within 4/3 of optimal
 * makespan, which is far inside the headroom this tier needs. Ties (equal
 * weight, or equal shard load) break on sorted path / lowest shard index, so
 * the same inputs always produce the same assignment.
 */
export function planShards(files: readonly string[], timings: Timings, shardCount: number): string[][] {
  if (!Number.isInteger(shardCount) || shardCount < 1) {
    throw new Error(`shard count must be a positive integer, got: ${shardCount}`);
  }
  const fallback = defaultWeight(timings);
  const unique = [...new Set(files)].sort();
  const ordered = [...unique].sort((a, b) => (timings[b] ?? fallback) - (timings[a] ?? fallback) || a.localeCompare(b));

  const shards: string[][] = Array.from({ length: shardCount }, () => []);
  const loads = new Array<number>(shardCount).fill(0);
  for (const file of ordered) {
    let lightest = 0;
    for (let i = 1; i < shardCount; i++) {
      if (loads[i]! < loads[lightest]!) lightest = i;
    }
    shards[lightest]!.push(file);
    loads[lightest] += timings[file] ?? fallback;
  }
  return shards.map((s) => s.sort());
}

export function parseShardSelector(selector: string): { index: number; count: number } {
  const m = /^([0-9]+)\/([0-9]+)$/.exec(selector);
  if (!m) throw new Error(`shard selector must be of the form k/N (e.g. 1/4); got: ${selector}`);
  const index = Number(m[1]);
  const count = Number(m[2]);
  if (count < 1) throw new Error(`shard count must be >= 1; got: ${selector}`);
  if (index < 1 || index > count) throw new Error(`shard index must be in 1..${count}; got: ${selector}`);
  return { index, count };
}

// CLI: file list on stdin (one path per line), selected shard on stdout.
//   find src -name '*.integration.test.ts' | node --import tsx src/test-shards.ts --shard 2/4
//   ... --plan 4      # human-readable projected load per shard
if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  const argv = process.argv.slice(2);
  const stdin = readFileSync(0, "utf8");
  const files = stdin
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
  const timings = loadTimings();

  const planAt = argv.indexOf("--plan");
  if (planAt !== -1) {
    const count = Number(argv[planAt + 1]);
    const shards = planShards(files, timings, count);
    const fallback = defaultWeight(timings);
    const unknown = files.filter((f) => timings[f] === undefined);
    shards.forEach((shard, i) => {
      const cost = shardCost(shard, timings, fallback);
      process.stdout.write(`shard ${i + 1}/${count}: ${shard.length} files, projected ${(cost / 1000).toFixed(1)}s\n`);
    });
    process.stdout.write(
      `${files.length} files, ${unknown.length} unmeasured (default ${(fallback / 1000).toFixed(1)}s each)\n`,
    );
    process.exit(0);
  }

  const shardAt = argv.indexOf("--shard");
  if (shardAt === -1) {
    process.stdout.write(files.join("\n") + (files.length > 0 ? "\n" : ""));
    process.exit(0);
  }
  const { index, count } = parseShardSelector(argv[shardAt + 1] ?? "");
  const shard = planShards(files, timings, count)[index - 1] ?? [];
  process.stdout.write(shard.join("\n") + (shard.length > 0 ? "\n" : ""));
}
